Repository GangbacOl/realtime-keyword, pull requests merged in 2021-09, with the labels that each got.

#2 [Refactor/#1] background 코드 리팩토링
  js/background.js
  js/background/Crawler.js
  js/background/Tester.js
  js/background/TrendCrawler.js
  js/background/index.html
  js/background/index.js
  js/background/utils.js
  manifest.json
Labels: refactor

#5 Fix/#4 keywords undefined로 나오는 버그 픽스
  js/popup.js
Labels: bug, invalid

#6 Docs/#3 README 업데이트
  README.md
  img/readme/readme-1.png
  img/readme/readme-2.png
  img/readme/readme-3.png
Labels: documentation

#8 docs: 이미지 가운데 정렬 업데이트
  README.md
Labels: documentation

#16 [Feature/#13] 선택할 수 있는 국가 선택하기
  js/background/GeoOptionPanel.js
  js/background/Tester.js
  js/background/constants.js
  js/background/index.js
Labels: enhancement
